### ISSUE TITLE
Addressenoder som ikke finnes lenger

### ISSUE THREAD

**Issue by FredrikLindseth** [rubund/addrnodeimport#20]
Jeg fjernet noen adresser som har blitt til bilvei her en dag, og kjapp som du er så var de tilbake på plass like etterpå. Eksempelvis https://www.openstreetmap.org/node/5696262724

Er det noe måte å hindre at slike kommer tilbake? 

Jeg antar at adressen forsvinner i rådataene til slutt, men det kan jo ta sin tid. Disse forsvant antakeligvis for et halv til ett helt år siden.

**Comment by rubund** [comment]
Hei,

Ok, så vi får etablere en svarteliste. Fint om du rapporterer alle slike du finner. :)

Ruben

**Comment by rubund** [comment]
Hei,
Er så sjelden jeg jobber med OpenStreetMap, at jeg glemte helt at vi har allerede en måte å håndtere disse på.
Endre "addr:housenumber" taggen til "abandoned:addr:housenumber" for nodene det gjelder. Da vil det ikke legges til på nytt.

Hilsen Ruben

**Comment by ghost** [comment]
Så jeg må beholde noden og endre taggene til  det følgende?
```
abandoned:addr:city=Bergen
abandoned:addr:housenumber=24
abandoned:addr:postcode=5005
abandoned:addr:street=Klosteret
```

Fant en annen variant av problemet, en node som ikke gir mening https://www.openstreetmap.org/node/3125999248, midt ute på plenen i en park.

**Comment by rubund** [comment]
jepp, alle bør endres, men addrnodeimport-skriptet sjekker bare addr:housenumber.
